### ISSUE TITLE
Skill fails to load

### ISSUE THREAD

**Issue by szanzibar** [moritzgloeckl/todoist-skill#3]
I get the following after installing the skill:

```
2022-03-17 02:20:33.679 | ERROR    |   586 | mycroft.skills.skill_loader:_create_skill_instance:295 | Skill __init__ failed with AttributeError("'dict' object has no attribute 'set_changed_callback'")
Traceback (most recent call last):
  File "/home/odroid/mycroft-core/mycroft/skills/skill_loader.py", line 292, in _create_skill_instance
    self.instance = skill_module.create_skill()
  File "/opt/mycroft/skills/todoist-skill.moritzgloeckl/__init__.py", line 121, in create_skill
    return TodoistSkill()
  File "/opt/mycroft/skills/todoist-skill.moritzgloeckl/__init__.py", line 51, in __init__
    self.settings.set_changed_callback(self._setup_api)
AttributeError: 'dict' object has no attribute 'set_changed_callback'
: 'dict' object has no attribute 'set_changed_callback'
2022-03-17 02:20:33.681 | ERROR    |   586 | mycroft.skills.skill_loader:_communicate_load_status:351 | Skill todoist-skill.moritzgloeckl failed to load

```

**Comment by moritzgloeckl** [comment]
Unfortunately I haven't updated this in a while and I'm not actively using Todoist anymore :/ If you like you can submit a PR to get this running again!
